# Generated by Django 5.1 on 2024-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_googleuser_google_id_remove_googleuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='google_id',
            field=models.CharField(default=1980, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
