# Generated by Django 5.1 on 2024-10-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_2fa_enabled',
        ),
    ]
