# Generated by Django 5.1 on 2024-10-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_googleuser_google_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleUser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
