# Generated by Django 5.1 on 2024-10-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_is_google_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_google_user',
        ),
    ]
