# Generated by Django 5.1.1 on 2024-10-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_passwordresetrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
    ]
