# Generated by Django 5.1.1 on 2024-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=2, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
